package:
  name: conda-content-trust
  version: {{ GIT_DESCRIBE_TAG }}+{{ GIT_BUILD_STR }}

source:
  # git_url only captures committed code
  git_url: ../

build:
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  noarch: python
  entry_points:
    - conda-content-trust = conda_content_trust.cli:cli

requirements:
  build:
    - git  # for source/git_url above
  host:
    - python
    - pip
    - hatchling >=1.12.2
    - hatch-vcs >=0.2.0
    - wheel
  run:
    - python
    - cryptography <41

test:
  source_files:
    - tests
  requires:
    - pytest
    - pytest-cov
    - ruamel_yaml
  commands:
    - pytest -v tests
    - conda-content-trust --help

about:
  home: https://github.com/conda/conda-content-trust
  summary: Signing and verification tools, geared toward the conda ecosystem
  description: >
    Based on The Update Framework (TUF), conda-content-trust contains a set of
    tools to enable package managers like conda to protect against tampering,
    so that when users obtain a package or data about that package, those users
    can know whether or not the data is trustworthy (e.g. originally comes from
    a reliable source and has not been tampered with). A basic library and
    basic CLI are included to provide signing, verification, and trust
    delegation functionality.  This exists as an alteration of TUF because of
    the very particular needs of the conda ecosystem. (Developers are
    encouraged to just use TUF whenever possible!)  This tool is general
    purpose. It is currently used in conda 4.10.1+ to verify package metadata
    signatures when they are available.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://github.com/conda/conda-content-trust
  dev_url: https://github.com/conda/conda-content-trust
