---
coverage:
  precision: 2
  round: nearest
  range: 60...100
  status:
    patch:
      default:
        informational: true
    project:
      default:
        informational: true

ignore:
  - tests/.*

comment: off
