# disable autofixing PRs, commenting "pre-commit.ci autofix" on a pull request triggers a autofix
ci:
    autofix_prs: false
# generally speaking we ignore all vendored code as well as tests data
exclude: |
  (?x)^(
    tests/testdata
  )/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # standard end of line/end of file cleanup
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: trailing-whitespace
      # ensure syntaxes are valid
      - id: check-toml
      - id: check-yaml
        exclude: ^(conda\.)?recipe/meta.yaml
      - id: check-json
      # catch git merge/rebase problems
      - id: check-merge-conflict
  # Python verification and formatting
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      # auto inject license blurb
      - id: insert-license
        files: \.py$
        args: [--license-filepath, .github/disclaimer.txt, --no-extra-eol]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
      # upgrade standard Python codes
      - id: pyupgrade
        args: [--py38-plus]
        exclude: ^conda/exports.py
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      # auto sort Python imports
      - id: isort
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      # auto format Python codes
      - id: black
  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.16.0
    hooks:
      # auto format Python codes within docstrings
      - id: blacken-docs
        additional_dependencies: [black]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      # lint Python codes
      - id: flake8
