# disable autofixing PRs, commenting "pre-commit.ci autofix" on a pull request triggers a autofix
ci:
    autofix_prs: false
# generally speaking we ignore all vendored code as well as tests data
exclude: |
  (?x)^(
    tests/testdata
  )/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      # standard end of line/end of file cleanup
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: trailing-whitespace
      # ensure syntaxes are valid
      - id: check-toml
      - id: check-yaml
        exclude: ^(conda\.)?recipe/meta.yaml
      - id: check-json
      # catch git merge/rebase problems
      - id: check-merge-conflict
      - id: fix-encoding-pragma
  - repo: https://github.com/akaihola/darker
    rev: 1.5.0
    hooks:
      - id: darker
        additional_dependencies: [black]
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        additional_dependencies: [black]
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: [--exit-zero]
  - repo: https://github.com/PyCQA/pylint
    rev: v2.14.4
    hooks:
      - id: pylint
        args: [--exit-zero]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: [--exit-zero]
        # ignore all tests, not just tests data
        exclude: ^tests/
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.0
    hooks:
      - id: insert-license
        files: \.py$
        args: [--license-filepath, .github/disclaimer.txt]
