{% set data = load_setup_py_data() %}

package:
  name: conda-content-trust
  version: {{ data['version'] }}

source:
  path: ..

build:
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .
  noarch: python
  entry_points:
    {% for entry in data['entry_points']['console_scripts'] %}
    - {{ entry.split('=')[0].strip() }} = {{ entry.split('=')[1].strip() }}
    {% endfor %}

requirements:
  host:
    - python
    - pip
  run:
    - python
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  source_files:
    - tests
  requires:
    - pytest
    - pytest-cov
    - ruamel_yaml
  commands:
    - pytest -v tests
    - conda-content-trust --help

about:
  home: https://github.com/conda/conda-content-trust
  summary: Signing and verification tools, geared toward the conda ecosystem
  description: >
    Based on The Update Framework (TUF), conda-content-trust contains a set of
    tools to enable package managers like conda to protect against tampering,
    so that when users obtain a package or data about that package, those users
    can know whether or not the data is trustworthy (e.g. originally comes from
    a reliable source and has not been tampered with). A basic library and
    basic CLI are included to provide signing, verification, and trust
    delegation functionality.  This exists as an alteration of TUF because of
    the very particular needs of the conda ecosystem. (Developers are
    encouraged to just use TUF whenever possible!)  This tool is general
    purpose. It is currently used in conda 4.10.1+ to verify package metadata
    signatures when they are available.
  license: BSD 3-Clause
  license_file: LICENSE
  doc_url: https://github.com/conda/conda-content-trust
  dev_url: https://github.com/conda/conda-content-trust
